[build]
builder = "nixpacks"

[deploy]
startCommand = "python backend/app/main.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[build.nixpacks]
providers = ["node", "python"]

[build.nixpacks.phases.setup]
nixpkgs = ["nodejs", "python310"]

[build.nixpacks.phases.install]
cmds = [
  "cd frontend && npm install",
  "cd frontend && npm run build"
]

[build.nixpacks.phases.build]
cmds = [
  "cd frontend && npm run build"
]

[build.nixpacks.phases.start]
cmd = "python backend/app/main.py"
